spring.application.name=gestaosaas

debug=true
spring.datasource.url=jdbc:h2:mem:gestaosaas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# PIX
pix.recebedor-nome=SMART BUSINESS
pix.chave=seu-pix@empresa.com
pix.expiracao-segundos=900
pix.webhook-token=token-seguro-123