services:
  postgres:
    image: postgres:16
    container_name: smart_postgres
    restart: always
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: smart
      POSTGRES_DB: smart_business
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: smart_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
